# Generated by Django 3.1.6 on 2021-02-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_remove_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcover',
            name='image_url',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='image',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
