# Generated by Django 3.1.6 on 2021-02-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_auto_20210211_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcover',
            name='hash_long',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='bookcover',
            name='hash_short',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
