# Generated by Django 3.1.6 on 2021-03-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0007_bookprice_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprice',
            name='price_type',
            field=models.PositiveIntegerField(choices=[(1, 'Offer'), (2, 'Request')], default=1),
            preserve_default=False,
        ),
    ]
