# Generated by Django 3.1.6 on 2021-03-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0008_bookprice_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
