# Generated by Django 3.1.6 on 2021-03-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0009_bookprice_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='matcher.book')),
            ],
        ),
        migrations.AddField(
            model_name='bookcover',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='covers', to='matcher.bookprofile'),
        ),
        migrations.AddField(
            model_name='bookprice',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='matcher.bookprofile'),
        ),
    ]
