# Generated by Django 3.1.6 on 2021-03-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0011_auto_20210308_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
