# Generated by Django 3.1.6 on 2021-03-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0012_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprofile',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
