# Generated by Django 3.1.6 on 2021-03-09 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0013_auto_20210308_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprice',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='matcher.source'),
        ),
    ]
