# Generated by Django 3.1.6 on 2021-03-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0014_auto_20210309_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(null=True, to='matcher.Author'),
        ),
    ]
