# Generated by Django 3.1.6 on 2021-03-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0016_auto_20210321_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprofile',
            name='books',
            field=models.ManyToManyField(to='matcher.Book'),
        ),
    ]
