# Generated by Django 3.1.6 on 2021-03-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0017_bookprofile_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookprofile',
            name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='matcher.Author'),
        ),
        migrations.AlterField(
            model_name='bookprofile',
            name='books',
            field=models.ManyToManyField(related_name='profiles', to='matcher.Book'),
        ),
    ]
