# Generated by Django 3.1.6 on 2021-03-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0018_auto_20210323_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprice',
            name='price_type',
            field=models.PositiveIntegerField(choices=[(1, 'Offer'), (2, 'Request'), (3, 'New'), (4, 'Used')]),
        ),
    ]
