# Generated by Django 3.1.6 on 2021-04-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0019_auto_20210328_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('price_type', models.PositiveIntegerField(choices=[(1, 'Offer'), (2, 'Request'), (3, 'New'), (4, 'Used')])),
                ('active', models.BooleanField(default=True)),
                ('devider_in_name', models.CharField(blank=True, max_length=1)),
            ],
        ),
    ]
