# Generated by Django 3.1.6 on 2021-04-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0020_bookimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookimport',
            name='auth_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bookimport',
            name='auth_password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
