# Generated by Django 3.1.6 on 2021-04-28 19:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0022_auto_20210416_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='other_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
